name: Build, Lint, Test and Deploy

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start Development Server
        run: npm run dev & sleep 10 && curl http://localhost:5173/
      # - name: Check if Development Server is available
      #   run: |
      #     sleep 10 # Wait for the server to start
      #     curl --retry 10 --retry-connrefused http://localhost:5173/
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run unit-test
      - name: Run e2e tests
        run: npm run e2e-test
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: e2e-tests/Reports
